apiVersion: v1
kind: Service
metadata:
  name: lab-portal-service
spec:
  type: NodePort
  selector:
    app: lab-portal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
